<Project>
  <PropertyGroup>
    <BrandName>Flect</BrandName>
    <BrandClsid>{4D038D4F-2125-48BE-8848-BA30A13AC7EA}</BrandClsid>
    <BrandAppId>{16C090EA-F07E-47B7-8811-B97D3BE26DDC}</BrandAppId>
    <BrandVersion>1.1</BrandVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <BrandShellDllName>$(BrandName)Shell</BrandShellDllName>
    <BrandAppExeName>$(BrandName)</BrandAppExeName>
    <BrandBuildDir>$(RepoRoot)build\</BrandBuildDir>
    <BrandDistDir>$(RepoRoot)dist\</BrandDistDir>
    <BrandThirdPartyDir>$(RepoRoot)dependencies\</BrandThirdPartyDir>
  </PropertyGroup>

</Project>
